In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')
df.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369

In [4]:
df.dtypes

engine_displacement      int64
num_cylinders          float64
horsepower             float64
vehicle_weight         float64
acceleration           float64
model_year               int64
origin                     str
fuel_type                  str
drivetrain                 str
num_doors              float64
fuel_efficiency_mpg    float64
dtype: object

In [5]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [6]:
df = df.fillna(0)

In [10]:
from sklearn.model_selection import train_test_split

df_full_train, df_test = train_test_split(df, test_size = 0.2, random_state=1)

df_train, df_val = train_test_split(df_full_train, test_size = 0.25, random_state=1)

y_train = df_train['fuel_efficiency_mpg'].values
y_val = df_val['fuel_efficiency_mpg'].values
y_test = df_test['fuel_efficiency_mpg'].values

del df_train['fuel_efficiency_mpg']
del df_val['fuel_efficiency_mpg']
del df_test['fuel_efficiency_mpg']

In [14]:
from sklearn.feature_extraction import DictVectorizer

train_dict = df_train.to_dict(orient='records')
val_dict = df_val.to_dict(orient='records')
test_dict = df_test.to_dict(orient='records')

dv = DictVectorizer(sparse = False)
X_train = dv.fit_transform(train_dict)
X_val = dv.transform(val_dict)
X_test = dv.transform(test_dict)

### Question 1

Let's train a decision tree regressor to predict the fuel_efficiency_mpg variable.

Train a model with max_depth=1.
Which feature is used for splitting the data?

In [15]:
from sklearn.tree import DecisionTreeRegressor

model = DecisionTreeRegressor(max_depth = 1, random_state = 42)

model.fit(X_train, y_train)

DecisionTreeRegressor(max_depth=1, random_state=42)

In [18]:
from sklearn.tree import export_text
print(export_text(model, feature_names=list(dv.get_feature_names_out())))

|--- vehicle_weight <= 3022.11
|   |--- value: [16.88]
|--- vehicle_weight >  3022.11
|   |--- value: [12.94]

### Question 2

Train a random forest regressor with these parameters:

- n_estimators=10
- random_state=1
- n_jobs=-1 (optional - to make training faster)

What's the RMSE of this model on the validation data?

In [19]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import root_mean_squared_error
model = RandomForestRegressor(n_estimators = 10, random_state = 1, n_jobs = -1)
model.fit(X_train, y_train)
y_pred = model.predict(X_val)

root_mean_squared_error(y_val, y_pred)

0.45707126026197337

### Question 3

Now let's experiment with the n_estimators parameter

- Try different values of this parameter from 10 to 200 with step 10.
- Set random_state to 1.
- Evaluate the model on the validation dataset.

After which value of n_estimators does RMSE stop improving? Consider 3 decimal places for calculating the answer.

In [21]:
scores = []

for n in range(10, 201, 10):
    model = RandomForestRegressor(n_estimators = n, random_state = 1, n_jobs = -1)

    model.fit(X_train, y_train)
    y_pred = model.predict(X_val)

    scores.append([n, round(root_mean_squared_error(y_val, y_pred), 3)])

scores_df = pd.DataFrame(scores, columns = ['n_estimators', 'rmse'])

scores_df

    n_estimators   rmse
0             10  0.457
1             20  0.452
2             30  0.450
3             40  0.448
4             50  0.446
5             60  0.445
6             70  0.445
7             80  0.445
8             90  0.444
9            100  0.444
10           110  0.443
11           120  0.443
12           130  0.443
13           140  0.443
14           150  0.442
15           160  0.442
16           170  0.442
17           180  0.442
18           190  0.442
19           200  0.442

### Question 4

Let's select the best max_depth:

- Try different values of max_depth: [10, 15, 20, 25]
- For each of these values,
    - try different values of n_estimators from 10 till 200 (with step 10)
    - calculate the mean RMSE
    - Fix the random seed: random_state=1
  
What's the best max_depth, using the mean RMSE?

In [22]:
scores = []

for d in [10, 15, 20, 25]:
    for n in range(10, 201, 10):
        
        model = RandomForestRegressor(n_estimators = n, max_depth = d, random_state = 1, n_jobs = -1)
        model.fit(X_train, y_train)
        y_pred = model.predict(X_val)
    
        scores.append([d, n, round(root_mean_squared_error(y_val, y_pred), 3)])

scores_df = pd.DataFrame(scores, columns = ['max_depth', 'n_estimators', 'rmse'])

In [23]:
scores_df.sort_values('rmse', ascending = False)

    max_depth  n_estimators   rmse
40         20            10  0.458
20         15            10  0.457
60         25            10  0.457
41         20            20  0.453
61         25            20  0.452
..        ...           ...    ...
15         10           160  0.440
14         10           150  0.440
13         10           140  0.440
12         10           130  0.440
10         10           110  0.440

[80 rows x 3 columns]

### Question 5

We can extract feature importance information from tree-based models.

At each step of the decision tree learning algorithm, it finds the best split. When doing it, we can calculate "gain" - the reduction in impurity before and after the split. This gain is quite useful in understanding what are the important features for tree-based models.

In Scikit-Learn, tree-based models contain this information in the feature_importances_ field.

For this homework question, we'll find the most important feature:

Train the model with these parameters:
- n_estimators=10,
- max_depth=20,
- random_state=1,
- n_jobs=-1 (optional)
- Get the feature importance information from this model
  
What's the most important feature (among these 4)?

In [24]:
model = RandomForestRegressor(n_estimators = 10, max_depth = 20, random_state = 1, n_jobs = -1)
model.fit(X_train, y_train)
model.feature_importances_

array([1.14536287e-02, 3.96650944e-04, 3.11283259e-04, 3.28170182e-03,
       3.69466267e-04, 3.01551010e-04, 1.60423301e-02, 3.16452511e-03,
       2.33145848e-03, 1.62794233e-03, 4.85137573e-04, 4.93652614e-04,
       5.64584351e-04, 9.59176087e-01])

In [29]:
importance_df = pd.DataFrame({
    'feature': dv.get_feature_names_out(),
    'importance': model.feature_importances_
}).sort_values('importance', ascending=False)

In [30]:
importance_df

                         feature  importance
13                vehicle_weight    0.959176
6                     horsepower    0.016042
0                   acceleration    0.011454
3            engine_displacement    0.003282
7                     model_year    0.003165
8                  num_cylinders    0.002331
9                      num_doors    0.001628
12                    origin=USA    0.000565
11                 origin=Europe    0.000494
10                   origin=Asia    0.000485
1     drivetrain=All-wheel drive    0.000397
4               fuel_type=Diesel    0.000369
2   drivetrain=Front-wheel drive    0.000311
5             fuel_type=Gasoline    0.000302

### Question 6

Now let's train an XGBoost model! 

For this question, we'll tune the eta parameter:

- Install XGBoost
- Create DMatrix for train and validation
- Create a watchlist
- Train a model with these parameters for 100 rounds:

```python
xgb_params = {
    'eta': 0.3, 
    'max_depth': 6,
    'min_child_weight': 1,
    
    'objective': 'reg:squarederror',
    'nthread': 8,
    
    'seed': 1,
    'verbosity': 1,
}
```

In [36]:
import xgboost as xgb
features = list(dv.get_feature_names_out())
dtrain = xgb.DMatrix(X_train, y_train, feature_names=features)
dval = xgb.DMatrix(X_val, y_val, feature_names=features)

In [41]:
watchlist = [(dtrain, 'train'), (dval, 'val')]

xgb_params = {
    'eta': 0.3, 
    'max_depth': 6,
    'min_child_weight': 1,
    
    'objective': 'reg:squarederror',
    'nthread': 8,
    
    'seed': 1,
    'verbosity': 1,
}

model = xgb.train(xgb_params, dtrain, num_boost_round=100, evals=watchlist)

[0]	train-rmse:1.81393	val-rmse:1.85444
[1]	train-rmse:1.31919	val-rmse:1.35353
[2]	train-rmse:0.98120	val-rmse:1.01316
[3]	train-rmse:0.75443	val-rmse:0.78667
[4]	train-rmse:0.60680	val-rmse:0.64318
[5]	train-rmse:0.51381	val-rmse:0.55664
[6]	train-rmse:0.45470	val-rmse:0.50321
[7]	train-rmse:0.41881	val-rmse:0.47254
[8]	train-rmse:0.39534	val-rmse:0.45509
[9]	train-rmse:0.38038	val-rmse:0.44564
[10]	train-rmse:0.37115	val-rmse:0.43896
[11]	train-rmse:0.36361	val-rmse:0.43594
[12]	train-rmse:0.35850	val-rmse:0.43558
[13]	train-rmse:0.35365	val-rmse:0.43394
[14]	train-rmse:0.35025	val-rmse:0.43349
[15]	train-rmse:0.34666	val-rmse:0.43362
[16]	train-rmse:0.34459	val-rmse:0.43378
[17]	train-rmse:0.34128	val-rmse:0.43405
[18]	train-rmse:0.33822	val-rmse:0.43391
[19]	train-rmse:0.33709	val-rmse:0.43374
[20]	train-rmse:0.33553	val-rmse:0.43376
[21]	train-rmse:0.33243	val-rmse:0.43453
[22]	train-rmse:0.33031	val-rmse:0.43510
[23]	train-rmse:0.32815	val-rmse:0.43601
[24]	train-rmse:0.32670	val-rmse:0.43592
[25]	train-rmse:0.32268	val-rmse:0.43683
[26]	train-rmse:0.32085	val-rmse:0.43678
[27]	train-rmse:0.32035	val-rmse:0.43681
[28]	train-rmse:0.31879	val-rmse:0.43719
[29]	train-rmse:0.31653	val-rmse:0.43739
[30]	train-rmse:0.31475	val-rmse:0.43752
[31]	train-rmse:0.31392	val-rmse:0.43782
[32]	train-rmse:0.31263	val-rmse:0.43761
[33]	train-rmse:0.31155	val-rmse:0.43764
[34]	train-rmse:0.31054	val-rmse:0.43793
[35]	train-rmse:0.30960	val-rmse:0.43784
[36]	train-rmse:0.30813	val-rmse:0.43828
[37]	train-rmse:0.30573	val-rmse:0.43891
[38]	train-rmse:0.30406	val-rmse:0.43924
[39]	train-rmse:0.30257	val-rmse:0.43946
[40]	train-rmse:0.30202	val-rmse:0.43968
[41]	train-rmse:0.29908	val-rmse:0.43978
[42]	train-rmse:0.29772	val-rmse:0.43998
[43]	train-rmse:0.29594	val-rmse:0.43969
[44]	train-rmse:0.29420	val-rmse:0.44009
[45]	train-rmse:0.29126	val-rmse:0.44024
[46]	train-rmse:0.28929	val-rmse:0.44041
[47]	train-rmse:0.28821	val-rmse:0.44101
[48]	train-rmse:0.28629	val-rmse:0.44096
[49]	train-rmse:0.28528	val-rmse:0.44142
[50]	train-rmse:0.28456	val-rmse:0.44140
[51]	train-rmse:0.28309	val-rmse:0.44160
[52]	train-rmse:0.28144	val-rmse:0.44109
[53]	train-rmse:0.28095	val-rmse:0.44152
[54]	train-rmse:0.27894	val-rmse:0.44191
[55]	train-rmse:0.27618	val-rmse:0.44225
[56]	train-rmse:0.27373	val-rmse:0.44265
[57]	train-rmse:0.27156	val-rmse:0.44310
[58]	train-rmse:0.26938	val-rmse:0.44276
[59]	train-rmse:0.26797	val-rmse:0.44282
[60]	train-rmse:0.26768	val-rmse:0.44290
[61]	train-rmse:0.26749	val-rmse:0.44285
[62]	train-rmse:0.26536	val-rmse:0.44311
[63]	train-rmse:0.26420	val-rmse:0.44329
[64]	train-rmse:0.26236	val-rmse:0.44360
[65]	train-rmse:0.26174	val-rmse:0.44352
[66]	train-rmse:0.26155	val-rmse:0.44360
[67]	train-rmse:0.25959	val-rmse:0.44410
[68]	train-rmse:0.25719	val-rmse:0.44487
[69]	train-rmse:0.25665	val-rmse:0.44476
[70]	train-rmse:0.25489	val-rmse:0.44531
[71]	train-rmse:0.25277	val-rmse:0.44563
[72]	train-rmse:0.25084	val-rmse:0.44632
[73]	train-rmse:0.25017	val-rmse:0.44649
[74]	train-rmse:0.24985	val-rmse:0.44661
[75]	train-rmse:0.24792	val-rmse:0.44628
[76]	train-rmse:0.24643	val-rmse:0.44671
[77]	train-rmse:0.24565	val-rmse:0.44667
[78]	train-rmse:0.24421	val-rmse:0.44633
[79]	train-rmse:0.24291	val-rmse:0.44663
[80]	train-rmse:0.24254	val-rmse:0.44689
[81]	train-rmse:0.24246	val-rmse:0.44692
[82]	train-rmse:0.24112	val-rmse:0.44705
[83]	train-rmse:0.23963	val-rmse:0.44721
[84]	train-rmse:0.23803	val-rmse:0.44704
[85]	train-rmse:0.23644	val-rmse:0.44749
[86]	train-rmse:0.23533	val-rmse:0.44757
[87]	train-rmse:0.23481	val-rmse:0.44756
[88]	train-rmse:0.23428	val-rmse:0.44778
[89]	train-rmse:0.23267	val-rmse:0.44809
[90]	train-rmse:0.23193	val-rmse:0.44839
[91]	train-rmse:0.23149	val-rmse:0.44844
[92]	train-rmse:0.23040	val-rmse:0.44863
[93]	train-rmse:0.22891	val-rmse:0.44896
[94]	train-rmse:0.22701	val-rmse:0.44922
[95]	train-rmse:0.22475	val-rmse:0.44904
[96]	train-rmse:0.22336	val-rmse:0.44954
[97]	train-rmse:0.22131	val-rmse:0.44979
[98]	train-rmse:0.22013	val-rmse:0.45040
[99]	train-rmse:0.21950	val-rmse:0.45018

In [42]:
xgb_params = {
    'eta': 0.1, 
    'max_depth': 6,
    'min_child_weight': 1,
    
    'objective': 'reg:squarederror',
    'nthread': 8,
    
    'seed': 1,
    'verbosity': 1,
}

model = xgb.train(xgb_params, dtrain, num_boost_round=100, evals=watchlist)

[0]	train-rmse:2.28944	val-rmse:2.34561
[1]	train-rmse:2.07396	val-rmse:2.12434
[2]	train-rmse:1.88066	val-rmse:1.92597
[3]	train-rmse:1.70730	val-rmse:1.74987
[4]	train-rmse:1.55163	val-rmse:1.59059
[5]	train-rmse:1.41247	val-rmse:1.44988
[6]	train-rmse:1.28796	val-rmse:1.32329
[7]	train-rmse:1.17660	val-rmse:1.20930
[8]	train-rmse:1.07736	val-rmse:1.10830
[9]	train-rmse:0.98883	val-rmse:1.02009
[10]	train-rmse:0.91008	val-rmse:0.94062
[11]	train-rmse:0.84030	val-rmse:0.87100
[12]	train-rmse:0.77874	val-rmse:0.80916
[13]	train-rmse:0.72417	val-rmse:0.75465
[14]	train-rmse:0.67626	val-rmse:0.70780
[15]	train-rmse:0.63402	val-rmse:0.66672
[16]	train-rmse:0.59690	val-rmse:0.63062
[17]	train-rmse:0.56447	val-rmse:0.60016
[18]	train-rmse:0.53619	val-rmse:0.57383
[19]	train-rmse:0.51138	val-rmse:0.55044
[20]	train-rmse:0.48983	val-rmse:0.53064
[21]	train-rmse:0.47135	val-rmse:0.51451
[22]	train-rmse:0.45501	val-rmse:0.49998
[23]	train-rmse:0.44120	val-rmse:0.48790
[24]	train-rmse:0.42929	val-rmse:0.47773
[25]	train-rmse:0.41881	val-rmse:0.46891
[26]	train-rmse:0.40953	val-rmse:0.46151
[27]	train-rmse:0.40173	val-rmse:0.45551
[28]	train-rmse:0.39470	val-rmse:0.45043
[29]	train-rmse:0.38873	val-rmse:0.44621
[30]	train-rmse:0.38342	val-rmse:0.44289
[31]	train-rmse:0.37876	val-rmse:0.43989
[32]	train-rmse:0.37450	val-rmse:0.43754
[33]	train-rmse:0.37073	val-rmse:0.43553
[34]	train-rmse:0.36743	val-rmse:0.43390
[35]	train-rmse:0.36435	val-rmse:0.43250
[36]	train-rmse:0.36178	val-rmse:0.43095
[37]	train-rmse:0.35927	val-rmse:0.42976
[38]	train-rmse:0.35713	val-rmse:0.42866
[39]	train-rmse:0.35506	val-rmse:0.42806
[40]	train-rmse:0.35343	val-rmse:0.42746
[41]	train-rmse:0.35195	val-rmse:0.42692
[42]	train-rmse:0.35024	val-rmse:0.42666
[43]	train-rmse:0.34862	val-rmse:0.42616
[44]	train-rmse:0.34714	val-rmse:0.42613
[45]	train-rmse:0.34621	val-rmse:0.42595
[46]	train-rmse:0.34477	val-rmse:0.42563
[47]	train-rmse:0.34342	val-rmse:0.42548
[48]	train-rmse:0.34217	val-rmse:0.42520
[49]	train-rmse:0.34097	val-rmse:0.42513
[50]	train-rmse:0.33998	val-rmse:0.42498
[51]	train-rmse:0.33860	val-rmse:0.42481
[52]	train-rmse:0.33767	val-rmse:0.42453
[53]	train-rmse:0.33651	val-rmse:0.42459
[54]	train-rmse:0.33560	val-rmse:0.42448
[55]	train-rmse:0.33480	val-rmse:0.42449
[56]	train-rmse:0.33386	val-rmse:0.42426
[57]	train-rmse:0.33292	val-rmse:0.42429
[58]	train-rmse:0.33196	val-rmse:0.42438
[59]	train-rmse:0.33105	val-rmse:0.42450
[60]	train-rmse:0.33054	val-rmse:0.42456
[61]	train-rmse:0.32953	val-rmse:0.42444
[62]	train-rmse:0.32872	val-rmse:0.42454
[63]	train-rmse:0.32777	val-rmse:0.42461
[64]	train-rmse:0.32673	val-rmse:0.42479
[65]	train-rmse:0.32602	val-rmse:0.42493
[66]	train-rmse:0.32489	val-rmse:0.42520
[67]	train-rmse:0.32397	val-rmse:0.42525
[68]	train-rmse:0.32338	val-rmse:0.42518
[69]	train-rmse:0.32275	val-rmse:0.42513
[70]	train-rmse:0.32202	val-rmse:0.42503
[71]	train-rmse:0.32161	val-rmse:0.42515
[72]	train-rmse:0.32060	val-rmse:0.42496
[73]	train-rmse:0.31996	val-rmse:0.42517
[74]	train-rmse:0.31963	val-rmse:0.42513
[75]	train-rmse:0.31895	val-rmse:0.42526
[76]	train-rmse:0.31825	val-rmse:0.42538
[77]	train-rmse:0.31755	val-rmse:0.42559
[78]	train-rmse:0.31742	val-rmse:0.42568
[79]	train-rmse:0.31702	val-rmse:0.42568
[80]	train-rmse:0.31667	val-rmse:0.42563
[81]	train-rmse:0.31656	val-rmse:0.42571
[82]	train-rmse:0.31569	val-rmse:0.42564
[83]	train-rmse:0.31547	val-rmse:0.42568
[84]	train-rmse:0.31475	val-rmse:0.42581
[85]	train-rmse:0.31440	val-rmse:0.42574
[86]	train-rmse:0.31352	val-rmse:0.42579
[87]	train-rmse:0.31285	val-rmse:0.42576
[88]	train-rmse:0.31243	val-rmse:0.42586
[89]	train-rmse:0.31146	val-rmse:0.42574
[90]	train-rmse:0.31059	val-rmse:0.42586
[91]	train-rmse:0.30997	val-rmse:0.42591
[92]	train-rmse:0.30943	val-rmse:0.42590
[93]	train-rmse:0.30817	val-rmse:0.42591
[94]	train-rmse:0.30699	val-rmse:0.42622
[95]	train-rmse:0.30625	val-rmse:0.42611
[96]	train-rmse:0.30565	val-rmse:0.42621
[97]	train-rmse:0.30557	val-rmse:0.42629
[98]	train-rmse:0.30486	val-rmse:0.42629
[99]	train-rmse:0.30419	val-rmse:0.42623