## About Dataset

Lending Club

Lending Club is a peer-to-peer Lending company based in the US. They match people looking to invest money with people looking to borrow money. When investors invest their money through Lending Club, this money is passed onto borrowers, and when borrowers pay their loans back, the capital plus the interest passes on back to the investors. It is a win for everybody as they can get typically lower loan rates and higher investor returns.

The Lending Club dataset contains complete loan data for all loans issued through the 2007-2015, including the current loan status (Current, Late, Fully Paid, etc.) and latest payment information. Features (aka variables) include credit scores, number of finance inquiries, address including zip codes and state, and collections among others. Collections indicates whether the customer has missed one or more payments and the team is trying to recover their money. The file is a matrix of about 890 thousand observations and 75 variables.

Target: Loan grade (A/B/C/D/E/F/G)

In [5]:
import numpy as np
import pandas as pd

In [17]:
pd.options.display.max_rows = None

In [3]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("adarshsng/lending-club-loan-data-csv")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'lending-club-loan-data-csv' dataset.
Path to dataset files: /kaggle/input/lending-club-loan-data-csv

In [6]:
import os
print(os.listdir(path))

['loan.csv', 'LCDataDictionary.xlsx']

In [7]:
df = pd.read_csv(os.path.join(path, 'loan.csv'), nrows = 500000)
df.head()

/tmp/ipykernel_63598/352506140.py:1: DtypeWarning: Columns (112,123,124,125,128,129,130,133,139,140,141) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(path, 'loan.csv'), nrows = 500000)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,2500,2500,2500.0,36 months,13.56,84.92,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,30000,30000,30000.0,60 months,18.94,777.23,D,D2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,5000,5000,5000.0,36 months,17.97,180.69,D,D1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,4000,4000,4000.0,36 months,18.94,146.51,D,D2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,30000,30000,30000.0,60 months,16.14,731.78,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
id,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
member_id,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
loan_amnt,500000.0,16006.670650,10131.255236,1000.00,8000.0000,14000.000,22000.0000,4.000000e+04
funded_amnt,500000.0,16006.670650,10131.255236,1000.00,8000.0000,14000.000,22000.0000,4.000000e+04
funded_amnt_inv,500000.0,16003.267372,10131.051724,725.00,8000.0000,14000.000,22000.0000,4.000000e+04
int_rate,500000.0,12.734626,5.151640,5.31,8.4600,11.800,16.0100,3.099000e+01
installment,500000.0,466.270114,286.871203,29.76,254.2700,386.760,628.4900,1.670150e+03
annual_inc,500000.0,80121.894450,89236.750361,0.00,46000.0000,66000.000,96000.0000,9.930475e+06
url,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
desc,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
dti,498867.0,19.647449,20.381570,0.00,11.4250,17.700,25.0100,9.990000e+02
delinq_2yrs,500000.0,0.230524,0.745528,0.00,0.0000,0.000,0.0000,5.800000e+01
inq_last_6mths,500000.0,0.443286,0.726025,0.00,0.0000,0.000,1.0000,5.000000e+00
mths_since_last_delinq,221098.0,36.847909,21.780217,0.00,19.0000,34.000,53.0000,2.260000e+02
mths_since_last_record,63801.0,83.140249,23.157820,1.00,68.0000,87.000,101.0000,1.270000e+02
open_acc,500000.0,11.493942,5.945068,0.00,7.0000,10.000,14.0000,1.010000e+02
pub_rec,500000.0,0.135366,0.387745,0.00,0.0000,0.000,0.0000,5.200000e+01
revol_bal,500000.0,16266.939862,22814.384879,0.00,5307.7500,10830.000,19856.2500,2.358150e+06
revol_util,499400.0,43.912646,24.908312,0.00,24.3000,42.100,62.3000,1.910000e+02
total_acc,500000.0,22.642062,12.105232,2.00,14.0000,21.000,29.0000,1.600000e+02
out_prncp,500000.0,12407.487755,9544.518500,0.00,4937.3400,10161.970,18239.0100,4.000000e+04
out_prncp_inv,500000.0,12405.054936,9544.358633,0.00,4935.8000,10154.100,18236.3350,4.000000e+04
total_pymnt,500000.0,4439.977458,5395.515294,0.00,1448.3150,2782.960,5261.5400,5.165339e+04
total_pymnt_inv,500000.0,4438.841877,5394.372996,0.00,1447.9925,2782.390,5260.9600,5.165339e+04
total_rec_prncp,500000.0,3363.838720,5038.691499,0.00,920.4300,1798.660,3529.5800,4.000000e+04
total_rec_int,500000.0,1069.652708,1083.348124,0.00,343.6200,712.450,1416.4525,1.998833e+04
total_rec_late_fee,500000.0,0.456081,5.476420,0.00,0.0000,0.000,0.0000,4.045300e+02
recoveries,500000.0,6.029950,158.453279,0.00,0.0000,0.000,0.0000,3.312207e+04
collection_recovery_fee,500000.0,1.049876,28.109199,0.00,0.0000,0.000,0.0000,5.961973e+03
last_pymnt_amnt,500000.0,1480.180881,4380.537913,0.00,268.0600,429.090,729.7100,4.135367e+04
collections_12_mths_ex_med,500000.0,0.017690,0.146510,0.00,0.0000,0.000,0.0000,9.000000e+00
mths_since_last_major_derog,116136.0,46.302869,21.605004,0.00,29.0000,46.000,64.0000,2.260000e+02
policy_code,500000.0,1.000000,0.000000,1.00,1.0000,1.000,1.0000,1.000000e+00
annual_inc_joint,69097.0,128316.829428,84285.211673,5693.51,85000.0000,114000.000,152000.0000,7.874821e+06
dti_joint,69097.0,19.356882,8.087348,0.00,13.3800,18.900,24.9600,4.397000e+01
acc_now_delinq,500000.0,0.000092,0.009591,0.00,0.0000,0.000,0.0000,1.000000e+00
tot_coll_amt,500000.0,214.572236,11608.181950,0.00,0.0000,0.000,0.0000,6.214661e+06
tot_cur_bal,500000.0,144013.782014,167447.757394,0.00,26917.0000,74690.000,218015.5000,9.971659e+06
open_acc_6m,500000.0,0.899448,1.122198,0.00,0.0000,1.000,1.0000,1.500000e+01
open_act_il,500000.0,2.701920,2.931475,0.00,1.0000,2.000,3.0000,5.600000e+01
open_il_12m,500000.0,0.673526,0.927919,0.00,0.0000,0.000,1.0000,8.000000e+00
open_il_24m,500000.0,1.527670,1.551953,0.00,0.0000,1.000,2.0000,2.000000e+01
mths_since_rcnt_il,481469.0,21.098976,25.777941,0.00,7.0000,13.000,25.0000,5.070000e+02
total_bal_il,500000.0,35324.859700,45447.870319,0.00,7862.0000,22465.000,45848.0000,1.837038e+06
il_util,418478.0,68.030883,23.801384,0.00,53.0000,71.000,85.0000,1.000000e+03
open_rv_12m,500000.0,1.229112,1.492544,0.00,0.0000,1.000,2.0000,2.600000e+01
open_rv_24m,500000.0,2.625178,2.569164,0.00,1.0000,2.000,4.0000,5.000000e+01
max_bal_bc,500000.0,5859.124640,5905.311923,0.00,2184.0000,4438.000,7765.0000,1.170668e+06
all_util,499871.0,54.124592,21.032054,0.00,40.0000,55.000,69.0000,2.390000e+02
total_rev_hi_lim,500000.0,38314.783214,37363.710345,0.00,16200.0000,28700.000,48700.0000,2.087500e+06
inq_fi,500000.0,1.086050,1.502308,0.00,0.0000,1.000,2.0000,3.800000e+01
total_cu_tl,500000.0,1.485164,2.668707,0.00,0.0000,0.000,2.0000,6.800000e+01
inq_last_12m,500000.0,1.939522,2.362115,0.00,0.0000,1.000,3.0000,6.700000e+01
acc_open_past_24mths,500000.0,4.429088,3.235789,0.00,2.0000,4.000,6.0000,5.400000e+01
avg_cur_bal,499960.0,13714.392697,17224.685777,0.00,2907.7500,7041.500,19038.0000,6.232290e+05
bc_open_to_buy,493344.0,15032.583033,19533.757651,0.00,2854.0000,8277.000,19653.0000,6.059960e+05
bc_util,493129.0,49.917558,29.007300,0.00,26.0000,48.900,74.4000,2.016000e+02
chargeoff_within_12_mths,500000.0,0.006820,0.093132,0.00,0.0000,0.000,0.0000,9.000000e+00
delinq_amnt,500000.0,1.935872,229.645421,0.00,0.0000,0.000,0.0000,6.500000e+04
mo_sin_old_il_acct,481469.0,122.987549,55.836468,0.00,85.0000,129.000,155.0000,8.480000e+02
mo_sin_old_rev_tl_op,500000.0,174.707254,100.375694,1.00,103.0000,156.000,226.0000,8.260000e+02
mo_sin_rcnt_rev_tl_op,500000.0,15.115978,18.741943,0.00,4.0000,9.000,19.0000,5.020000e+02
mo_sin_rcnt_tl,500000.0,8.708980,9.615583,0.00,3.0000,6.000,11.0000,3.820000e+02
mort_acc,500000.0,1.338708,1.709776,0.00,0.0000,1.000,2.0000,8.700000e+01
mths_since_recent_bc,493740.0,25.543130,33.799363,0.00,6.0000,15.000,30.0000,6.610000e+02
mths_since_recent_bc_dlq,99310.0,40.427298,22.253549,0.00,23.0000,38.000,57.0000,1.940000e+02
mths_since_recent_inq,438102.0,7.479849,6.062516,0.00,2.0000,6.000,11.0000,2.500000e+01
mths_since_recent_revol_delinq,144397.0,37.700624,21.980704,0.00,20.0000,35.000,53.0000,1.900000e+02
num_accts_ever_120_pd,500000.0,0.468766,1.368539,0.00,0.0000,0.000,0.0000,5.800000e+01
num_actv_bc_tl,500000.0,3.613906,2.422435,0.00,2.0000,3.000,5.0000,5.000000e+01
num_actv_rev_tl,500000.0,5.362316,3.432705,0.00,3.0000,5.000,7.0000,7.200000e+01
num_bc_sats,500000.0,4.838416,3.179726,0.00,3.0000,4.000,6.0000,6.900000e+01
num_bc_tl,500000.0,7.097690,4.522616,0.00,4.0000,6.000,9.0000,8.600000e+01
num_il_tl,500000.0,8.174430,7.357114,0.00,3.0000,6.000,11.0000,1.300000e+02
num_op_rev_tl,500000.0,8.164014,4.935060,0.00,5.0000,7.000,10.0000,9.100000e+01
num_rev_accts,500000.0,12.928354,7.897874,2.00,7.0000,11.000,17.0000,1.510000e+02
num_rev_tl_bal_gt_0,500000.0,5.325532,3.366109,0.00,3.0000,5.000,7.0000,6.500000e+01
num_sats,500000.0,11.473030,5.939192,0.00,7.0000,10.000,14.0000,1.010000e+02
num_tl_120dpd_2m,487564.0,0.000004,0.002025,0.00,0.0000,0.000,0.0000,1.000000e+00
num_tl_30dpd,500000.0,0.000080,0.008944,0.00,0.0000,0.000,0.0000,1.000000e+00
num_tl_90g_dpd_24m,500000.0,0.060094,0.420170,0.00,0.0000,0.000,0.0000,5.800000e+01
num_tl_op_past_12m,500000.0,2.032170,1.890880,0.00,1.0000,2.000,3.0000,2.600000e+01
pct_tl_nvr_dlq,499998.0,94.571131,9.096725,0.00,92.3000,100.000,100.0000,1.000000e+02
percent_bc_gt_75,493336.0,32.950558,35.029754,0.00,0.0000,25.000,57.1000,1.000000e+02
pub_rec_bankruptcies,500000.0,0.123466,0.335485,0.00,0.0000,0.000,0.0000,7.000000e+00
tax_liens,500000.0,0.011474,0.186843,0.00,0.0000,0.000,0.0000,5.200000e+01
tot_hi_cred_lim,500000.0,184961.051608,188634.609927,0.00,52074.7500,116396.500,269224.2500,9.999999e+06
total_bal_ex_mort,500000.0,51919.935824,53359.841600,0.00,19544.0000,37560.000,66109.2500,2.622906e+06
total_bc_limit,500000.0,26647.399166,25804.935464,0.00,9800.0000,19200.000,35100.0000,1.569000e+06
total_il_high_credit_limit,500000.0,45679.547804,47938.562309,0.00,14940.0000,33756.500,61897.0000,2.118996e+06
revol_bal_joint,68985.0,34757.049634,29599.112949,0.00,15477.0000,27350.000,45215.0000,1.110019e+06
sec_app_inq_last_6mths,68985.0,0.607538,0.969398,0.00,0.0000,0.000,1.0000,6.000000e+00
sec_app_mort_acc,68985.0,1.538189,1.766506,0.00,0.0000,1.000,2.0000,2.700000e+01
sec_app_open_acc,68985.0,11.486497,6.670732,0.00,7.0000,10.000,15.0000,6.700000e+01
sec_app_revol_util,67788.0,57.108528,25.836450,0.00,38.3000,59.100,77.8000,4.343000e+02
sec_app_open_act_il,68985.0,2.998043,3.236424,0.00,1.0000,2.000,4.0000,4.300000e+01
sec_app_num_rev_accts,68985.0,12.517707,8.211074,0.00,7.0000,11.000,17.0000,1.060000e+02
sec_app_chargeoff_within_12_mths,68985.0,0.041748,0.390470,0.00,0.0000,0.000,0.0000,2.100000e+01
sec_app_collections_12_mths_ex_med,68985.0,0.070943,0.393264,0.00,0.0000,0.000,0.0000,2.300000e+01
sec_app_mths_since_last_major_derog,22377.0,37.326183,23.803320,0.00,17.0000,36.000,57.0000,1.850000e+02
deferral_term,332.0,3.000000,0.000000,3.00,3.0000,3.000,3.0000,3.000000e+00
hardship_amount,332.0,190.263524,153.504755,5.95,80.9650,140.915,271.4675,8.452200e+02
hardship_length,332.0,3.000000,0.000000,3.00,3.0000,3.000,3.0000,3.000000e+00
hardship_dpd,332.0,12.231928,9.504513,0.00,2.0000,11.500,20.0000,2.900000e+01
orig_projected_additional_accrued_interest,283.0,561.394664,457.897812,17.85,240.7200,403.920,796.1850,2.535660e+03
hardship_payoff_balance_amount,332.0,14868.847349,9525.400040,424.11,7533.6675,12780.660,21029.9000,4.014935e+04
hardship_last_payment_amount,332.0,194.526898,210.542525,0.03,31.5750,132.445,298.0250,1.072990e+03
settlement_amount,493.0,6702.659797,4800.767983,413.93,3103.0000,5410.000,9236.0000,2.850300e+04
settlement_percentage,493.0,53.297059,9.449085,30.48,45.0000,50.000,65.0000,9.000000e+01
settlement_term,493.0,17.894523,6.354135,1.00,16.0000,18.000,24.0000,3.000000e+01

#### Check missing values

In [19]:
df.isnull().sum().sort_values(ascending=False)

id                                            500000
member_id                                     500000
url                                           500000
desc                                          500000
orig_projected_additional_accrued_interest    499717
hardship_dpd                                  499668
hardship_amount                               499668
hardship_length                               499668
hardship_end_date                             499668
hardship_status                               499668
hardship_start_date                           499668
hardship_reason                               499668
hardship_type                                 499668
hardship_last_payment_amount                  499668
hardship_loan_status                          499668
hardship_payoff_balance_amount                499668
payment_plan_start_date                       499668
deferral_term                                 499668
debt_settlement_flag_date                     499507
settlement_amount                             499507
settlement_status                             499507
settlement_percentage                         499507
settlement_term                               499507
settlement_date                               499507
sec_app_mths_since_last_major_derog           477623
mths_since_last_record                        436199
verification_status_joint                     435877
sec_app_revol_util                            432212
sec_app_earliest_cr_line                      431015
sec_app_num_rev_accts                         431015
sec_app_inq_last_6mths                        431015
sec_app_chargeoff_within_12_mths              431015
revol_bal_joint                               431015
sec_app_mort_acc                              431015
sec_app_open_act_il                           431015
sec_app_open_acc                              431015
sec_app_collections_12_mths_ex_med            431015
dti_joint                                     430903
annual_inc_joint                              430903
mths_since_recent_bc_dlq                      400690
mths_since_last_major_derog                   383864
mths_since_recent_revol_delinq                355603
mths_since_last_delinq                        278902
il_util                                        81522
mths_since_recent_inq                          61898
emp_title                                      54940
next_pymnt_d                                   49861
emp_length                                     42256
mths_since_rcnt_il                             18531
mo_sin_old_il_acct                             18531
num_tl_120dpd_2m                               12436
bc_util                                         6871
percent_bc_gt_75                                6664
bc_open_to_buy                                  6656
mths_since_recent_bc                            6260
dti                                             1133
last_pymnt_d                                     644
revol_util                                       600
all_util                                         129
avg_cur_bal                                       40
title                                             14
last_credit_pull_d                                 7
pct_tl_nvr_dlq                                     2
loan_amnt                                          0
term                                               0
loan_status                                        0
issue_d                                            0
verification_status                                0
annual_inc                                         0
home_ownership                                     0
sub_grade                                          0
installment                                        0
grade                                              0
funded_amnt_inv                                    0
funded_amnt                                        0
int_rate                                           0
pub_rec                                            0
revol_bal                                          0
out_prncp_inv                                      0
open_acc                                           0
inq_last_6mths                                     0
delinq_amnt                                        0
chargeoff_within_12_mths                           0
acc_open_past_24mths                               0
inq_last_12m                                       0
max_bal_bc                                         0
total_rev_hi_lim                                   0
inq_fi                                             0
total_cu_tl                                        0
open_rv_12m                                        0
open_rv_24m                                        0
open_acc_6m                                        0
tot_cur_bal                                        0
open_act_il                                        0
open_il_12m                                        0
open_il_24m                                        0
total_bal_il                                       0
policy_code                                        0
collections_12_mths_ex_med                         0
application_type                                   0
acc_now_delinq                                     0
tot_coll_amt                                       0
total_acc                                          0
initial_list_status                                0
out_prncp                                          0
total_rec_prncp                                    0
total_pymnt_inv                                    0
total_pymnt                                        0
total_rec_int                                      0
collection_recovery_fee                            0
recoveries                                         0
total_rec_late_fee                                 0
last_pymnt_amnt                                    0
pymnt_plan                                         0
purpose                                            0
zip_code                                           0
addr_state                                         0
delinq_2yrs                                        0
earliest_cr_line                                   0
num_tl_op_past_12m                                 0
pub_rec_bankruptcies                               0
total_bc_limit                                     0
total_il_high_credit_limit                         0
tot_hi_cred_lim                                    0
total_bal_ex_mort                                  0
tax_liens                                          0
num_il_tl                                          0
num_op_rev_tl                                      0
num_rev_accts                                      0
mo_sin_old_rev_tl_op                               0
mo_sin_rcnt_rev_tl_op                              0
mo_sin_rcnt_tl                                     0
mort_acc                                           0
num_actv_bc_tl                                     0
num_actv_rev_tl                                    0
num_accts_ever_120_pd                              0
num_tl_90g_dpd_24m                                 0
num_rev_tl_bal_gt_0                                0
num_tl_30dpd                                       0
num_sats                                           0
num_bc_sats                                        0
num_bc_tl                                          0
hardship_flag                                      0
disbursement_method                                0
debt_settlement_flag                               0
dtype: int64

In [ ]:
numerical = list(df.dtypes[df.dtypes != 'object'].index)
categorical = list(df.dtypes[df.dtypes == 'object'].index)
categorical

['term',
 'grade',
 'sub_grade',
 'emp_title',
 'emp_length',
 'home_ownership',
 'verification_status',
 'issue_d',
 'loan_status',
 'pymnt_plan',
 'purpose',
 'title',
 'zip_code',
 'addr_state',
 'earliest_cr_line',
 'initial_list_status',
 'last_pymnt_d',
 'next_pymnt_d',
 'last_credit_pull_d',
 'application_type',
 'verification_status_joint',
 'sec_app_earliest_cr_line',
 'hardship_flag',
 'hardship_type',
 'hardship_reason',
 'hardship_status',
 'hardship_start_date',
 'hardship_end_date',
 'payment_plan_start_date',
 'hardship_loan_status',
 'disbursement_method',
 'debt_settlement_flag',
 'debt_settlement_flag_date',
 'settlement_status',
 'settlement_date']

#### Check variable variance

In [22]:
df[numerical].apply(lambda x: x.std()).sort_values()

policy_code                                        0.000000
hardship_length                                    0.000000
deferral_term                                      0.000000
num_tl_120dpd_2m                                   0.002025
num_tl_30dpd                                       0.008944
acc_now_delinq                                     0.009591
chargeoff_within_12_mths                           0.093132
collections_12_mths_ex_med                         0.146510
tax_liens                                          0.186843
pub_rec_bankruptcies                               0.335485
pub_rec                                            0.387745
sec_app_chargeoff_within_12_mths                   0.390470
sec_app_collections_12_mths_ex_med                 0.393264
num_tl_90g_dpd_24m                                 0.420170
inq_last_6mths                                     0.726025
delinq_2yrs                                        0.745528
open_il_12m                                        0.927919
sec_app_inq_last_6mths                             0.969398
open_acc_6m                                        1.122198
num_accts_ever_120_pd                              1.368539
open_rv_12m                                        1.492544
inq_fi                                             1.502308
open_il_24m                                        1.551953
mort_acc                                           1.709776
sec_app_mort_acc                                   1.766506
num_tl_op_past_12m                                 1.890880
inq_last_12m                                       2.362115
num_actv_bc_tl                                     2.422435
open_rv_24m                                        2.569164
total_cu_tl                                        2.668707
open_act_il                                        2.931475
num_bc_sats                                        3.179726
acc_open_past_24mths                               3.235789
sec_app_open_act_il                                3.236424
num_rev_tl_bal_gt_0                                3.366109
num_actv_rev_tl                                    3.432705
num_bc_tl                                          4.522616
num_op_rev_tl                                      4.935060
int_rate                                           5.151640
total_rec_late_fee                                 5.476420
num_sats                                           5.939192
open_acc                                           5.945068
mths_since_recent_inq                              6.062516
settlement_term                                    6.354135
sec_app_open_acc                                   6.670732
num_il_tl                                          7.357114
num_rev_accts                                      7.897874
dti_joint                                          8.087348
sec_app_num_rev_accts                              8.211074
pct_tl_nvr_dlq                                     9.096725
settlement_percentage                              9.449085
hardship_dpd                                       9.504513
mo_sin_rcnt_tl                                     9.615583
total_acc                                         12.105232
mo_sin_rcnt_rev_tl_op                             18.741943
dti                                               20.381570
all_util                                          21.032054
mths_since_last_major_derog                       21.605004
mths_since_last_delinq                            21.780217
mths_since_recent_revol_delinq                    21.980704
mths_since_recent_bc_dlq                          22.253549
mths_since_last_record                            23.157820
il_util                                           23.801384
sec_app_mths_since_last_major_derog               23.803320
revol_util                                        24.908312
mths_since_rcnt_il                                25.777941
sec_app_revol_util                                25.836450
collection_recovery_fee                           28.109199
bc_util                                           29.007300
mths_since_recent_bc                              33.799363
percent_bc_gt_75                                  35.029754
mo_sin_old_il_acct                                55.836468
mo_sin_old_rev_tl_op                             100.375694
hardship_amount                                  153.504755
recoveries                                       158.453279
hardship_last_payment_amount                     210.542525
delinq_amnt                                      229.645421
installment                                      286.871203
orig_projected_additional_accrued_interest       457.897812
total_rec_int                                   1083.348124
last_pymnt_amnt                                 4380.537913
settlement_amount                               4800.767983
total_rec_prncp                                 5038.691499
total_pymnt_inv                                 5394.372996
total_pymnt                                     5395.515294
max_bal_bc                                      5905.311923
hardship_payoff_balance_amount                  9525.400040
out_prncp_inv                                   9544.358633
out_prncp                                       9544.518500
funded_amnt_inv                                10131.051724
funded_amnt                                    10131.255236
loan_amnt                                      10131.255236
tot_coll_amt                                   11608.181950
avg_cur_bal                                    17224.685777
bc_open_to_buy                                 19533.757651
revol_bal                                      22814.384879
total_bc_limit                                 25804.935464
revol_bal_joint                                29599.112949
total_rev_hi_lim                               37363.710345
total_bal_il                                   45447.870319
total_il_high_credit_limit                     47938.562309
total_bal_ex_mort                              53359.841600
annual_inc_joint                               84285.211673
annual_inc                                     89236.750361
tot_cur_bal                                   167447.757394
tot_hi_cred_lim                               188634.609927
id                                                      NaN
member_id                                               NaN
url                                                     NaN
desc                                                    NaN
dtype: float64

In [25]:
df['chargeoff_within_12_mths'].value_counts()

chargeoff_within_12_mths
0    496896
1      2888
2       167
3        27
4        14
6         3
7         2
5         2
9         1
Name: count, dtype: int64

In [26]:
df['policy_code'].value_counts()

policy_code
1    500000
Name: count, dtype: int64

In [27]:
df['hardship_length'].value_counts()

hardship_length
3.0    332
Name: count, dtype: int64

In [28]:
df['deferral_term'].value_counts()

deferral_term
3.0    332
Name: count, dtype: int64

In [29]:
df['num_tl_120dpd_2m'].value_counts()

num_tl_120dpd_2m
0.0    487562
1.0         2
Name: count, dtype: int64

In [36]:
from sklearn.feature_selection import VarianceThreshold

selector = VarianceThreshold(threshold=0.01)  # tune this

numeric_cols = df.select_dtypes(include='number').columns

selector.fit(df[numeric_cols])

# See which columns are kept
kept = numeric_cols[selector.get_support()]
dropped = numeric_cols[~selector.get_support()]
print("Dropped:", dropped.tolist())

Dropped: ['id', 'member_id', 'url', 'desc', 'policy_code', 'acc_now_delinq', 'chargeoff_within_12_mths', 'num_tl_120dpd_2m', 'num_tl_30dpd', 'deferral_term', 'hardship_length']

/usr/local/lib/python3.12/dist-packages/sklearn/feature_selection/_variance_threshold.py:114: RuntimeWarning: Degrees of freedom <= 0 for slice.
  self.variances_ = np.nanvar(X, axis=0)

In [37]:
len(dropped)

11

In [ ]:
new_df = df.copy()
new_df.drop(['policy_code', 'hardship_length', 'deferral_term'], axis = 1, inplace=True)

In [12]:
dict = pd.read_excel(os.path.join(path, 'LCDataDictionary.xlsx'))
dict

               LoanStatNew                                        Description
0           acc_now_delinq  The number of accounts on which the borrower i...
1     acc_open_past_24mths         Number of trades opened in past 24 months.
2               addr_state  The state provided by the borrower in the loan...
3                 all_util              Balance to credit limit on all trades
4               annual_inc  The self-reported annual income provided by th...
..                     ...                                                ...
148      settlement_amount  The loan amount that the borrower has agreed t...
149  settlement_percentage  The settlement amount as a percentage of the p...
150        settlement_term  The number of months that the borrower will be...
151                    NaN                                                NaN
152                    NaN  * Employer Title replaces Employer Name for al...

[153 rows x 2 columns]

In [16]:
for col in categorical:
    print(col, df[col].nunique())
    if df[col].nunique() < 10:
        print(df[col].value_counts())
    print()

term 2
term
36 months    348291
60 months    151709
Name: count, dtype: int64

grade 7
grade
B    142750
A    136102
C    128281
D     69621
E     19223
F      3328
G       695
Name: count, dtype: int64

sub_grade 35

emp_title 130441

emp_length 11

home_ownership 4
home_ownership
MORTGAGE    241585
RENT        197199
OWN          60728
ANY            488
Name: count, dtype: int64

verification_status 3
verification_status
Not Verified       201230
Source Verified    198473
Verified           100297
Name: count, dtype: int64

issue_d 13

loan_status 7
loan_status
Current               439326
Fully Paid             42298
Charged Off             7563
Late (31-120 days)      6565
In Grace Period         2909
Late (16-30 days)       1330
Default                    9
Name: count, dtype: int64

pymnt_plan 2
pymnt_plan
n    499893
y       107
Name: count, dtype: int64

purpose 13

title 12

zip_code 898

addr_state 50

earliest_cr_line 684

initial_list_status 2
initial_list_status
w    430893
f     69107
Name: count, dtype: int64

last_pymnt_d 29

next_pymnt_d 4
next_pymnt_d
Mar-2019    449989
Feb-2019       107
Apr-2019        42
Dec-2018         1
Name: count, dtype: int64

last_credit_pull_d 30

application_type 2
application_type
Individual    430903
Joint App      69097
Name: count, dtype: int64

verification_status_joint 3
verification_status_joint
Not Verified       28410
Source Verified    21833
Verified           13880
Name: count, dtype: int64

sec_app_earliest_cr_line 645

hardship_flag 2
hardship_flag
N    499864
Y       136
Name: count, dtype: int64

hardship_type 1
hardship_type
INTEREST ONLY-3 MONTHS DEFERRAL    332
Name: count, dtype: int64

hardship_reason 9
hardship_reason
NATURAL_DISASTER         93
UNEMPLOYMENT             70
EXCESSIVE_OBLIGATIONS    55
INCOME_CURTAILMENT       47
MEDICAL                  34
REDUCED_HOURS            22
DISABILITY                5
FAMILY_DEATH              4
DIVORCE                   2
Name: count, dtype: int64

hardship_status 3
hardship_status
COMPLETED    147
ACTIVE       136
BROKEN        49
Name: count, dtype: int64

hardship_start_date 19

hardship_end_date 21

payment_plan_start_date 19

hardship_loan_status 5
hardship_loan_status
Late (16-30 days)     130
Current               101
In Grace Period        85
Late (31-120 days)     13
Issued                  3
Name: count, dtype: int64

disbursement_method 2
disbursement_method
Cash         428641
DirectPay     71359
Name: count, dtype: int64

debt_settlement_flag 2
debt_settlement_flag
N    499507
Y       493
Name: count, dtype: int64

debt_settlement_flag_date 19

settlement_status 3
settlement_status
ACTIVE      400
BROKEN       48
COMPLETE     45
Name: count, dtype: int64

settlement_date 21

In [10]:
df['emp_length']

0         10+ years
1         10+ years
2           6 years
3         10+ years
4         10+ years
            ...
499995    10+ years
499996    10+ years
499997      2 years
499998     < 1 year
499999    10+ years
Name: emp_length, Length: 500000, dtype: object